// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3WzqsH1eZbNjvYd6iNOTwCMyPYpKuLJg',
    appId: '1:543236963801:web:8acfba528e00e473046dc8',
    messagingSenderId: '543236963801',
    projectId: 'onbuy-auction',
    authDomain: 'onbuy-auction.firebaseapp.com',
    storageBucket: 'onbuy-auction.appspot.com',
    measurementId: 'G-VZ3LCFRLSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyk6xGWOvbZU3ll-EvVOV5NmwOcu2Ay2s',
    appId: '1:543236963801:android:57f27c9883b6c038046dc8',
    messagingSenderId: '543236963801',
    projectId: 'onbuy-auction',
    storageBucket: 'onbuy-auction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI_mFHJONhpJ5xycoI03-yR1PQ32Jc6XU',
    appId: '1:543236963801:ios:eeadc61f73fd0c1a046dc8',
    messagingSenderId: '543236963801',
    projectId: 'onbuy-auction',
    storageBucket: 'onbuy-auction.appspot.com',
    iosClientId: '543236963801-s0n9hu45t5jj8gclaaqrl49t5t3vfd5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.onBuyAuction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI_mFHJONhpJ5xycoI03-yR1PQ32Jc6XU',
    appId: '1:543236963801:ios:eeadc61f73fd0c1a046dc8',
    messagingSenderId: '543236963801',
    projectId: 'onbuy-auction',
    storageBucket: 'onbuy-auction.appspot.com',
    iosClientId: '543236963801-s0n9hu45t5jj8gclaaqrl49t5t3vfd5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.onBuyAuction',
  );
}
